http:
  routers:
    rivaflow:
      rule: "Host(`72.60.41.251`) || Host(`srv973361.hstgr.cloud`)"
      service: rivaflow-frontend
      entryPoints:
        - web
        - websecure

    rivaflow-api:
      rule: "(Host(`72.60.41.251`) || Host(`srv973361.hstgr.cloud`)) && PathPrefix(`/api`)"
      service: rivaflow-backend
      entryPoints:
        - web
        - websecure

  services:
    rivaflow-frontend:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:3000"

    rivaflow-backend:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8000"
